In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np?

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

In [4]:
L1=list(range(10))

In [5]:
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L1[0])

int

In [11]:
type(L1)

list

In [13]:
L2=[str(c) for c in L1]

In [14]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
L3=[1,'X']

In [18]:
type(L3[1])

str

In [19]:
L4=[True, "2", 3.0, 4]

In [22]:
[type(item) for item in L4]

[bool, str, float, int]

In [24]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [25]:
L5=np.array([1,2,3,4])

In [27]:
type(L5[0])

numpy.int64

In [28]:
L6=np.array([1,2.0,3])

In [29]:
L6

array([1., 2., 3.])

In [31]:
type(L6[1])

numpy.float64

In [34]:
L7=np.array([1,'x',2.3])

In [35]:
L7

array(['1', 'x', '2.3'], dtype='<U32')

In [37]:
type(L7[1])

numpy.str_

In [44]:
np.array([1, 2.8, 3, 4], dtype=np.float32)

array([1. , 2.8, 3. , 4. ], dtype=float32)

In [53]:
L8=np.array([range(i,i+2) for i in [2,4,5]])

In [54]:
L8

array([[2, 3],
       [4, 5],
       [5, 6]])

In [56]:
# Create a length-10 integer array filled with 0s
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [68]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [69]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
np.random.random((3,3))

array([[0.59968378, 0.64390753, 0.89335373],
       [0.02890286, 0.81753755, 0.74982382],
       [0.08442953, 0.41613747, 0.19022245]])

In [78]:
np.random.normal(0,1,(3,3))

array([[ 0.11959287,  0.20361149, -0.43294322],
       [ 1.81353447,  2.841856  ,  1.89936211],
       [-0.13086843, -0.01229365,  0.407669  ]])

In [82]:
np.random.randint(0,10,(3,3))

array([[7, 1, 2],
       [4, 1, 9],
       [9, 8, 5]])

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.empty(3)

array([1., 1., 1.])

In [88]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)